theme: jekyll-theme-cayman
title: 'Java-Projects'
page_title: 'Jumpstart Open-Source with Java'
description: 'Start Your Open-Source Journey with Java Projects'
logo: 'assets/img/favicon.ico'
defaults:
  - scope:
      path: ''
    values:
      image: 
        path: 'assets/img/page-cover.png'
        height: 630
        width: 1200
exclude:
  - .gitignore
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - LICENSE

# For reference, Jekyll SEO Tag:
# https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/template.html